name: Build and deploy services

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  NUMBERS_DIRECTORY: ./code/serviceone
  NUMBERS_AZURE_WEBAPP_PACKAGE_PATH: ./code/serviceone/published
  LETTERS_DIRECTORY: ./code/servicetwo
  LETTERS_AZURE_WEBAPP_PACKAGE_PATH: ./code/servicetwo/published
  MERGE_DIRECTORY: ./code/servicethree
  MERGE_AZURE_WEBAPP_PACKAGE_PATH: ./code/servicethree/published
  FE_DIRECTORY: ./code/frontend
  FE_AZURE_WEBAPP_PACKAGE_PATH: ./code/frontend/published
  TEST_DIRECTORY: ./code/tests


  TEST_DIRECTORY: ./code/tests
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: dotnet test "${{ env.TEST_DIRECTORY }}" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

  build-numbers-service:
    runs-on: ubuntu-latest
    needs: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.NUMBERS_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ env.NUMBERS_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: Publish
        run: dotnet publish "${{ env.NUMBERS_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.NUMBERS_AZURE_WEBAPP_PACKAGE_PATH }}"
      
      - name: publish numbers service to Azure
        run: az
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

